### ISSUE TITLE
Is missing activation function (such as ReLU etc) intentional

### ISSUE THREAD

**Issue by aelluswamy-tesla** [Cyanogenoid/dspn#1]
In the resnet convolutional encoder in https://github.com/Cyanogenoid/dspn/blob/master/dspn/model.py#L109 there is no activation function following the batchnorm layer. Is this intentional. If so, why what this decision made?

**Comment by Cyanogenoid** [comment]
The only purpose of that self.end module is to turn the 4x4 feature map -- the output of the ResNet-34 -- into a 1x1 feature map. I didn't think that ReLUs were necessary there since the ResNet does most of the learning anyway, so I just left them out. I didn't experiment much with different self.end, since this one worked well enough.

(Sorry for the late reply, I somehow missed your issue!)
